apiVersion: v1
kind: Deployment
metadata:
  name: my-webapp
  labels:
    name: my-webapp
    env: dev
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
  selectors:
    matchlabels:
      name: my-webapp
  template:
    metadata:
      labels:
        name: my-webapp
    spec:
      containers:
        - name: webapp
          image: vsrekul/{$MY_IMAGE}          
          port:
            - containerPort: 80
          env:    
            - name: db_host
              valueFrom:
                configMapKeyRef:
                  name: env_vars
                  key: db_host
          volumeMounts:
          - name: pgp-key-volume
            mountPath: /root/.gnupg
            subPath: your_pgp_key.asc
          - name: secrets-volume
            mountPath: /app/secrets.enc.yaml
            subPath: secrets.enc.yaml
      volumes:
      - name: pgp-key-volume
        secret:
          secretName: pgp-key
      - name: secrets-volume
        secret:
          secretName: encrypted-secrets

    